export const DELETE_EMAIL = 'DELETE_EMAIL';
export const SELECT_EMAIL = 'SELECT_EMAIL';
export const SELECT_ALL_EMAILS = 'SELECT_ALL_EMAILS';
export const FILTER_BY = 'FILTER_BY';
export const SEARCH_FILTER = 'SEARCH_FILTER';
export const FETCH_EMAILS = 'FETCH_EMAILS';
export const CHANGE_EMAIL_STATUS = 'CHANGE_EMAIL_STATUS';

export const TABLE_TYPE = 'TABLE_TYPE';
